[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Milan Bhandari <milanbhandari@college.harvard.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
image = "0.23"
rayon = "1.5"